# This script calculates compactness measures for the plans generated by
# all the algorithm and the existing plan.

library(redist)
load("src/data.RData")
load("src/mcmc.RData")
load("src/smc.RData")

# MCMC
start.time <- Sys.time()
mcmc.compact <-
  redist.compactness(
    shp = df,
    district_membership = mcmc.out$partitions,
    measure = c("PolsbyPopper", "FryerHolden", "EdgesRemoved"),
    population = df$pop,
    adjacency = adjlist,
    counties = df$COUNTYFP,
    ncores = 4
  )
end.time <- Sys.time()
print(end.time - start.time)

# SMC
start.time <- Sys.time()
smc.compact <-
  redist.compactness(
    shp = df,
    district_membership = smc.out$cdvec,
    measure = c("PolsbyPopper", "FryerHolden", "EdgesRemoved"),
    population = df$pop,
    adjacency = adjlist,
    counties = df$COUNTYFP,
    ncores = 4
  )
end.time <- Sys.time()
print(end.time - start.time)

# Control
start.time <- Sys.time()
control.compact <-
  redist.compactness(
    shp = df,
    district_membership = df$CON_DIST,
    measure = c("PolsbyPopper", "FryerHolden", "EdgesRemoved"),
    population = df$pop,
    adjacency = adjlist,
    counties = df$COUNTYFP,
    ncores = 4
  )
end.time <- Sys.time()
print(end.time - start.time)

raw.compact <-
  list(
    mcmc = mcmc.compact,
    smc = smc.compact,
    control = control.compact
  )

save(raw.compact, file = "src/compact.raw.RData")
