# This script makes the pretty maps for my results section. 

library(tidyverse)
library(sf)

load("data/data_va.RData")
load("data/smc.100.RData")
load("data/crsg.100.RData")
load("data/compact.calc.100.RData")

plot_mean_dists <- function(data, alg) {
  data %>%
    as_tibble() %>%
    mutate(row_n = row_number()) %>%
    rowwise() %>%
    mutate(p_cd = as.integer(round(mean(c_across(V1:V100))))) %>%
    nest(cols = starts_with("V")) %>%
    inner_join(df, by = "row_n") %>%
    st_as_sf() %>%
    ggplot(aes(fill = factor(p_cd))) +
      geom_sf(size = 0, color = NA) +
      scale_fill_manual(values = colors) +
      coord_sf(datum = NA) +
      theme_void() +
      labs(
        title = paste0("Mean districts generated by ", alg),
        fill = "District #"
      )
}

plot_dist <- function(data, alg, n, measure=NULL, savename=NULL) {
  t = paste0(alg, " map")
  if(!is.null(measure))
    t = paste0(alg, " map with greatest ", measure, " score")
  data %>%
    as_tibble() %>%
    select(n) %>%
    mutate(row_n = row_number()) %>%
    rename(p_cd = 1) %>%
    inner_join(df, by = "row_n") %>%
    st_as_sf() %>%
    ggplot(aes(fill = factor(p_cd))) +
      geom_sf(size = 0, color = NA, show.legend = FALSE) +
      scale_fill_manual(values = colors) +
      coord_sf(datum = NA) +
      theme_void() +
      labs(
        title = t,
        fill = "District #"
      )
  if(!is.null(savename))
    ggsave(paste0("paper/img/",savename,".png"))
}

plot_rand_dists <- function(data, alg) {
  n <- sample(ncol(data), 1)
  plot_dist(data, alg, n)
}

plot_highest_pp <- function(data, compact, alg, savename) {
  # get index of most compact map
  n <- which.max(compact$pp)
  plot_dist(data, alg, n, measure = "Polsby-Popper", savename=savename)
}

plot_highest_ecc <- function(data, compact, alg, savename) {
  # get index of most compact map
  n <- which.max(compact$ecc)
  plot_dist(data, alg, n, measure = "Edge-Cut Compactness", savename=savename)
}

smc.pp <- plot_highest_pp(
  smc.out$cdvec, calc.compact$smc, "SMC", "map.smc.pp")
smc.ecc <- plot_highest_ecc(
  smc.out$cdvec, calc.compact$smc, "SMC", "map.smc.ec")

crsg.pp <- plot_highest_pp(
  crsg.out$partitions, calc.compact$crsg, "CRSG", "map.crsg.pp")
crsg.ecc <- plot_highest_ecc(
  crsg.out$partitions, calc.compact$crsg, "CRSG", "map.crsg.ecc")

control <- plot_dist(df$CON_DIST, "Control", 1, savename="map.control")
