---
title: "CRSG"
output: html_document
---

```{r}
library(tidyverse)
library(sf)
library(redist)
library(sp)
library(spData)
library(spdep)

precinct <- st_read("C:/Users/madie/OneDrive/data/pre-redist/VA_precinct_2018_nonan/VA_precinct_2018_nonan.shp")
```

```{r}
precinct$CON_DIST <- as.numeric(precinct$CON_DIST)
adjlist <- redist.adjacency(precinct)
area <- sf::st_area(precinct)
centers <- sf::st_coordinates(sf::st_centroid(precinct))
# DON'T need to do thisreplace NA populations with 0
#precinct$pop[is.na(precinct$pop)] <- 0
# add row_n as unique precinct identifier to join on
precinct$row_n <- seq.int(nrow(precinct))
# optimal color palette 
colors <- c("#DA618D", "#85D7D4", "#044b62", "#D5D160", "#e7854b", "#6cc32f", "#A87ADA", "#DAB8D3", "#C843DB", "#329349", "#78A5D5")
```

```{r}
# must round pop to integers since required by CRSG (estimates b/c ACS)
precinct$pop <- round(precinct$pop)
```

```{r}
class(precinct$pop)
```
```{r}
precinct %>% 
  ggplot(aes(fill = pop)) + 
  geom_sf(size = 0, show.legend = TRUE, color = NA) + 
  scale_fill_viridis_c(option = "magma") + 
  coord_sf(datum = NA) +
  theme_void() + 
  labs(title = "Population map of Virginia, by precinct", caption = "2018 ACS estimates")
```
```{r}
class(area)
```


```{r}
start.time <- Sys.time()
crsg.out <- redist.crsg(adj.list = adjlist, 
                        area = area, 
                        population = precinct$pop, 
                        x_center = centers[,1], 
                        y_center = centers[,2], 
                        ndists = 11, 
                        thresh = .01)
end.time <- Sys.time()
print(end.time - start.time)

save(crsg.out, file = "crsg_vac_2018_0.01_.RData")
```
```{r}
precinct %>%        
    ggplot(aes(fill = factor(crsg.out$district_membership))) +
      geom_sf(size = 0, color = NA) +
      scale_fill_manual(values = colors) +
      coord_sf(datum = NA) +
      theme_void() + 
      labs(
          title = "Hypothetical districts - CRSG - 0.01 pop parity"
           )
```

```{r}
dm <- crsg.out$district_membership
dmmat <- matrix(dm, nrow = length(dm), ncol = 1)
parity <- redist.parity(district_membership = dmmat,
                        population = precinct$pop)
```

```{r}
parity
```

